-- Fishing Log Data
-- coding: utf-8 'ä

FishingPole = 104 -- legacy category value; no longer used to validate fishing rods
Region = { Eriador=1, Rhovanion=2, Gondor=3, Mordor=4, Haradwaith=5 }
RegN = {}
for name,ix in pairs(Region) do RegN[ix] = name end
Cat = {  C="Cooking", G="General", J="Junk", Q="Quest", T="Trophy" }
Tier = { "Apprentice", "Journeyman", "Expert", "Artisan", "Master", 
	"Supreme", "Westfold", "Eastemnet", "Westemnet", "Anorien", 
	"Doomfold", "Ironfold", "Minas Ithil", "Gundabad", "Umbar" }
Prof = {"Apprentice","Journeyman","Expert","Master"}

ID = {	
		["1079A"] = {n="Amberjack", c="Q" },
		["2FD79"] = {n="Avanc", c="Q" },
		["29B25"] = {n="Avanc-tail", c="Q" },
		["26AD3"] = {n="Bad Fish", c="Q" },
		["3F9E7"] = {n="Bait Fish", c="Q" },
		["0EFF8"] = {n="Ball of Gunk", c="JQ", v=1 },
		["0F13A"] = {n="Bandfin Darter", c="G", v=29 },
		["0EF5E"] = {n="Barbel", c="G", v=1 },
		["0F173"] = {n="Barbarous Barbel", c="T" },
		["26AD4"] = {n="Big Fish", c="Q" },
		["0F172"] = {n="Big Mouth Bass", c="T" },
		["0EF68"] = {n="Bitterling", c="G", v=1 },
		["0F141"] = {n="Blackfin Darter", c="G", v=29 },
		["4D554"] = {n="Bleak", c="G", v=63 },
		["2FD3A"] = {n="Blood-fish", c="Q" },
		["0F133"] = {n="Bloodfin Darter", c="G", v=29 },
		["0F182"] = {n="Bright Bitterling", c="T" },
		["0F179"] = {n="Brawny Bullhead", c="T" },
		["4D557"] = {n="Bream", c="G", v=63 },
		["4D54C"] = {n="Broken Barrel", c="J", v=69 },
		["0EFCF"] = {n="Brown Trout", c="C", t=1, v=29 },
		["0EFD6"] = {n="Bull Trout", c="C", t=1, v=29 },
		["0EF66"] = {n="Bullhead", c="G", v=1 },
		["4D55A"] = {n="Burbot", c="G", v=72 },
		["3F9E4"] = {n="Calembel Carp", c="Q" },
		["0EF5D"] = {n="Carp", c="C", t=6, v=14 },
		["0EF6A"] = {n="Catfish", c="C", t=2, v=1 },
		["1079E"] = {n="Celebhal", c="Q" },
		["2AAAA"] = {n="Chair", c="Q" },
		["0EF5B"] = {n="Charr", c="G", v=1 },
		["4D548"] = {n="Chub", c="G", v=69 },
		["0F178"] = {n="Colourful Charr", c="T" },
		["0F183"] = {n="Courageous Carp", c="T" },
		["0F16F"] = {n="Cunning Catfish", c="T" },
		["0EFCD"] = {n="Cutthroat Trout", c="C", t=1, v=29 },
		["0EF67"] = {n="Dace", c="C", t=1, v=1 },
		["6B1E0"] = {n="Deep Fish", c="Q" },
		["0F17B"] = {n="Delightful Dace", c="T" },
		["26B52"] = {n="Dinner Fish", c="Q" },
		["0EFF7"] = {n="Dirty Skull", c="J", v=63 },
		["0EFF2"] = {n="Drift-wood", c="J", v=1 },
		["1079C"] = {n="Drum", c="Q" },
		["0F127"] = {n="Dwarf Sturgeon", c="G", v=29 },
		["26B10"] = {n="Easy Fish", c="Q" },
		["0F174"] = {n="Fantastic Flounder", c="T" },
		["0F137"] = {n="Firebelly Darter", c="G", v=29 },
		["0EF61"] = {n="Flounder", c="C", t=5, v=14 },
		["40B63"] = {n="Flounder", c="Q" },
		["69DE3"] = {n="Fresh Fish", c="Q" },
		["0F142"] = {n="Fringbarbel Sturgeon", c="G", v=29 },
		["2FD3B"] = {n="Garsfeld Guppy", c="Q" },
		["0F175"] = {n="Gleaming Grayling", c="T" },
		["0EF64"] = {n="Golden Mullet", c="C", t=4, v=14 },
		["10899"] = {n="Golden Redfish", c="Q" },
		["0EFD0"] = {n="Golden Trout", c="C", t=1, v=29 },
		["0EF58"] = {n="Goldfish", c="G", v=1 },
		["0EF63"] = {n="Grayling", c="G", v=13 },
		["0F17C"] = {n="Great Golden Mullet", c="T" },
		["0F17A"] = {n="Giant Goldfish", c="T" },

		["6EB9D"] = {n="Glittering Fish", c="Q" },
		["0F132"] = {n="Green Sturgeon", c="G", v=29 },
		["0F11E"] = {n="Greenfin Darter", c="G", v=29 },
		["4D556"] = {n="Gudgeon", c="G", v=63 },
		["2AAAD"] = {n="Hat", c="Q" },
		["0EF65"] = {n="Houting", c="G", v=13 },
		["2FD33"] = {n="Huge Fish", c="Q" },
		["0F176"] = {n="Huge Houting", c="T" },
		["0EF8A"] = {n="Ice Bay Salmon", c="Q" },
		["0F130"] = {n="Lake Sturgeon", c="G", v=29 },
		["0EFCE"] = {n="Lake Trout", c="C", t=1, v=29 },
		["3F9E6"] = {n="Lamedon Salmon", c="Q" },
		["3F9E5"] = {n="Lamedon Turtle", c="Q" },
		["4D549"] = {n="Lamprey", c="G", v=69 },
		["10893"] = {n="Large Fish", c="Q" },
		["2FD36"] = {n="Large Fish", c="Q" },
		["0EF5C"] = {n="Largemouth Bass", c="C", t=5, v=14 },
		["2AAAE"] = {n="List of Lost Goods", c="Q" },
		["4D546"] = {n="Loach", c="G", v=63 },
		["0F12B"] = {n="Longfin Darter", c="G", v=29 },
		["4D547"] = {n="Long Lake Salmon", c="G", v=72 },
		["1079B"] = {n="Luillim", c="Q" },
		["29B26"] = {n="Lurker Moss", c="Q" },
		["0F17E"] = {n="Magnificent Minnow", c="T" },
		["0B0D8"] = {n="Mathom", c="Q" },
		["10890"] = {n="Medium Fish", c="Q" },
		["2FD37"] = {n="Medium Fish", c="Q" },
		["0EE77"] = {n="Minnow", c="G", v=1 },
		["0F177"] = {n="Nasty Nine-spined Stickleback", c="T" },
		["0EF62"] = {n="Nine-spined Stickleback", c="G", v=13 },
		["0EAAC"] = {n="Oily Fish", c="Q" },
		["0EFF5"] = {n="Old Boot", c="JQ", v=1 },
		["4D552"] = {n="Old Glove", c="GQ", v=63 },
		["3975F"] = {n="Old River-king", c="Q" },
		["0F128"] = {n="Orangefin Darter", c="G", v=29 },
		["4D54E"] = {n="Orfe", c="G", v=63 },
		["0F11F"] = {n="Pallid Sturgeon", c="G", v=29 },
		["0EF60"] = {n="Perch", c="C", t=3, v=14 },
		["0F17D"] = {n="Perfect Perch", c="T" },
		["0F181"] = {n="Perfect Pike", c="T" },
		["0EF5F"] = {n="Pike", c="G", v=13 },
		["4D555"] = {n="Pollan", c="G", v=63 },
		["26B12"] = {n="Possible Fish", c="Q" },
		["4D54A"] = {n="Powan", c="G", v=63 },
		["4D551"] = {n="Pumpkinseed", c="G", v=69 },
		["26AD5"] = {n="Puny Fish", c="Q" },
		["0EFD4"] = {n="Rainbow Trout", c="C", t=1, v=29 },
		["0EFD2"] = {n="Red-spotted Trout", c="C", t=1, v=29 },
		["0EFD1"] = {n="Redband Trout", c="C", t=1, v=29 },
		["0F124"] = {n="Redfin Darter", c="G", v=29 },
		["4D54F"] = {n="Roach", c="G", v=69 },
		["0EFF3"] = {n="Rusty Axe", c="JQ", v=1 },
		["0EFF6"] = {n="Rusty Dagger", c="JQ", v=1 },
		["0EFF1"] = {n="Rusty Hammer", c="JQ", v=1 },
		["0EFFA"] = {n="Rusty Mace", c="JQ", v=1 },
		["0EFF4"] = {n="Rusty Sword", c="JQ", v=1 },
		["4D550"] = {n="Rusty Tankard", c="G", v=69 },
		["4D553"] = {n="Ruffe", c="G", v=63 },
		["0EF5A"] = {n="Rudd", c="G", v=1 },
		["0F180"] = {n="Ruthless Rudd", c="T" },
		["29B28"] = {n="Severed Hand", c="Q" },
		["0F136"] = {n="Shortnose Sturgeon", c="G", v=29 },
		["0F120"] = {n="Shovelnose Sturgeon", c="G", v=29 },
		["10895"] = {n="Silver Haddock", c="Q" },
		["46C5E"] = {n="Silvery Pout", c="Q" },
		["26B11"] = {n="Simple Fish", c="Q" },
		["10897"] = {n="Small Fish", c="Q" },
		["0EF69"] = {n="Smelt", c="G", v=1 },
		["0EFD3"] = {n="Speckled Trout", c="C", t=1, v=29 },
		["2AAAB"] = {n="Spectacles", c="Q" },
		["0F139"] = {n="Splendid Darter", c="G", v=29 },
		["4D54B"] = {n="Sprat", c="G", v=63 },
		["10894"] = {n="Starry Flounder", c="Q" },
		["0F126"] = {n="Starry Sturgeon", c="G", v=29 },
		["4D558"] = {n="Sunbleak", c="G", v=63 },
		["0F170"] = {n="Superb Smelt", c="T" },
		["2AAAC"] = {n="Tea-cup", c="Q" },
		["4D55D"] = {n="Tench", c="G", v=69 },
		["0EF59"] = {n="Three-spined Stickleback", c="G", v=13 },
		["4D55B"] = {n="Tilapia", c="G", v=69 },
		["26B13"] = {n="Tricky Fish", c="Q" },
		["0F17F"] = {n="Tricky Three-spined Stickleback", c="T" },
		["29B29"] = {n="Turtle Egg", c="Q" },
		["26B14"] = {n="Unlikely Fish", c="Q" },
		["4D54D"] = {n="Vendace", c="G", v=63 },
		["29B24"] = {n="Worn Relic of Time", c="Q" },
		["0EFF9"] = {n="Weeds", c="J", v=1 },
		["0B0D9"] = {n="Well-kept Mathom", c="Q" },
		["59716"] = {n="Wildwood Minnow", c="Q" },
		["0F13E"] = {n="White Sturgeon", c="G", v=29 },
		["4D559"] = {n="Zander", c="G", v=72 },
		["0F22E"] = {n="2-pound Salmon", c="T" },
		["0F229"] = {n="4-pound Salmon", c="T" },
		["0F226"] = {n="6-pound Salmon", c="T" },
		["0F22A"] = {n="10-pound Salmon", c="T" },
		["0F22B"] = {n="15-pound Salmon", c="T" },
		["0F228"] = {n="20-pound Salmon", c="T" },
		["0F227"] = {n="30-pound Salmon", c="T" },
		["0F22D"] = {n="40-pound Salmon", c="T" },
		["0F22C"] = {n="50-pound Salmon", c="T" },
	}
Quest = {
	{l=5, n="Refkell", loc="13.8s,103.2w", s="Thorin's Hall", 
		r=1, rn="Ered Luin", t="Fish-tales", c=90,
		nt="Trains fishing & free rod" },
	{l=5, n="Estmar Bolger", loc="33.4s,75.3w", s="Michel Delving", 
		r=1, rn="The Shire", t="One Fish, Two Fish", c=90,
		nt="Trains fishing & free rod" },
	{l=5, n="Henry Oakeshott", loc="30.4s,51.7w", s="Bree", 
		r=1, rn="Bree-land", t="Teach a Man to Fish", c=90,
		nt="Trains fishing & free rod" },
	{l=5, n="Ingul Ovestoke", loc="13.8s,103.2w", s="Thorin's Hall", 
		r=1, rn="Ered Luin", t="Barrel of fish", 
		nt="Requires Hard Tack Event in progress" },
	{l=5, n="Flobert Chubb", loc="31.2s,70.0w", s="Bywater", 
		r=1, rn="The Shire", t="Fishy. Very Fishy.", c=0,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Melia Pott", loc="31.2s,69.9w", s="Bywater", 
		r=1, rn="The Shire", t="The Great Mathom Fishing Swap", c=4,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Bollo Bolger", loc="31.3s,69.9w", s="Bywater", 
		r=1, rn="The Shire", t="Big Fish, Little Fish", c=0,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Goldie Tunnelly", loc="31.3s,69.9w", s="Bywater", 
		r=1, rn="The Shire", t="Pond, or Thief?", c=5,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Petunia Hornblower", loc="31.2s,70.0w", s="Bywater", 
		r=1, rn="The Shire", t="Hired Hook", c=5,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Neddie Grubb", loc="31.2s,70.0w", s="Bywater", 
		r=1, rn="The Shire", t="Stocking the Pond", c=6,
		nt="Requires Farmers Faire Festival in progress" },
	{l=5, n="Neddie Grubb", loc="31.2s,70.0w", s="Furtherholm", 
		r=5, rn="Zír Aktar", t="Fishing for Advice", c=0,
		nt="Requires Midsummer Festival in progress" },
	{l=5, n="Merkhâma", loc="3.8s,119.0w", s="Bywater", 
		r=1, rn="The Shire", t="The Fishing-hole", c=0,
		nt="Requires Farmers Faire Festival in progress" },
	{l=40, n="Haldúr", loc="29.6s,3.3w", s="Last Homely House", 
		r=1, rn="Rivendell", t="Hook, Line, and Sinker", c=2135,
		nt="Trains fishing & free rod" },
	{l=41, n="Barhador", loc="38.5s,19.9w", s="Tham Lumren", 
		r=1, rn="Trollshaws", t="Distaste for Vegetables", c=2170,
		nt="Requires quest accepted, A Roadside Respite" },
	{l=45, n="Wildwood Bulletin", loc="17.7s,54.4w", s="Trestlebridge", 
		r=1, rn="North Downs", t="Fish of the Wildwood", c=2310, },
	{l=46, n="Tapio", loc="18.2n,81.2w", s="Kuru-leir", 
		r=1, rn="Forochel", t="Bounty of the Sea", c=3752,
		nt="Requires Gauredain defeated at Hylje-leiri" },
	{l=47, n="Nôra", loc="19.5n,71.4w", s="Sûri-kylä", 
		r=1, rn="Forochel", t="Empty Larder", c=2380, },
	{l=75, n="Bron", loc="80.1s,16.8w", s="Galtrev", d=true,
		r=1, rn="Dunland", t="Glinting in Forgotten Pools", c=0,
		nt="Switch back to weapons after a catch." },
	{l=85, n="Héalac", loc="60.4s,62.3w", s="Snowbourn", d=true,
		r=2, rn="East Rohan", t="Cuts of Fish", c=3635,
		nt="Requires Aiding the Eastemnet (in Hytbold)" },
	{l=85, n="Héalac", loc="60.4s,62.3w", s="Snowbourn", d=true,
		r=2, rn="East Rohan", t="Terror of the Deep", c=3635,
		nt="Requires Aiding the Eastemnet (in Hytbold)" },
	{l=85, n="Héalac", loc="60.4s,62.3w", s="Snowbourn", d=true,
		r=2, rn="East Rohan", t="The Blood-fish", c=3635,
		nt="Requires Aiding the Eastemnet (in Hytbold)" },
	{l=85, n="Héalac", loc="60.4s,62.3w", s="Snowbourn", d=true,
		r=2, rn="East Rohan", t="The Garsfeld Guppy", c=3635,
		nt="Requires Aiding the Eastemnet (in Hytbold)" },
	{l=87, n="Théolac", loc="61.3s,73.6w", s="Edoras",
		r=2, rn="West Rohan", t="The Last Cast", c=3675,
		nt="Not available after Edoras evacuation." },
	{l=87, n="Old River-king", loc="62.7s,74.7w", s="Edoras",
		r=2, rn="West Rohan", t="The Old River King", c=3675,
		nt="Not available after Edoras evacuation." },
	{l=99, n="Anírwen", loc="75.1s,70.3w", s="Docks of Dol Amroth", 
		r=3, rn="West Gondor", t="Fishing on the Wharf", c=3915, d=true },
	{l=100, n="Torchuil", loc="75.3s,71.3w", s="Dol Amroth",
		r=3, rn="West Gondor", t="Baiting the Hook", c=0, d=true,
		nt="Requires quest, Dol Amroth - Joining the City Guard" },
	{l=100, n="Torchuil", loc="75.3s,71.3w", s="Dol Amroth",
		r=3, rn="West Gondor", t="The Bait Ball", c=0, d=true,
		nt="Requires quest, Dol Amroth - Joining the City Guard" },
	{l=100, n="Torchuil", loc="75.3s,71.3w", s="Dol Amroth",
		r=3, rn="West Gondor", t="The Salmon Run", c=0, d=true,
		nt="Requires quest, Dol Amroth - Joining the City Guard" },
	{l=100, n="Torchuil", loc="75.3s,71.3w", s="Dol Amroth",
		r=3, rn="West Gondor", t="Turtles in the Depths", c=0, d=true,
		nt="Requires quest, Dol Amroth - Joining the City Guard" },
	{l=105, n="Haldil", loc="89.5s,65.5w", s="Cathlond", c=4035,
		r=3, rn="Cape of Belfalas Homesteads", t="Fishing the Day Away", },
	{l=120, n="Radagast", loc="0.8n,52.6w", s="Radagast's Cottage",
		r=2, rn="Vales of Anduin", t="Rhosgobel: Cleaning the Anduin", c=1814, d=true,
		nt="Requires quest, A Message from Rhosgobel" },
	{l=120, n="Radagast", loc="0.8n,52.6w", s="Radagast's Cottage",
		r=2, rn="Vales of Anduin", t="Rhosgobel: Cleaning the Tributaries", c=1814, d=true,
		nt="Requires quest, A Message from Rhosgobel" },
}